#!/usr/bin/env python3
"""Money Sort: MERGE-SORT level generator (forward-gen + BFS filter + par bands).

Mechanic:
  - Notes carry a tier 0..TOP ($1,$5,$20,$100,$500 => tiers 0..4).
  - Move = pour the top run of equal-tier notes onto a wallet whose top is the
    same tier, or onto an empty wallet (unless source is already uniform).
  - MERGE: after a pour, if the dest's top run reaches MERGE_N equal notes of a
    tier t<TOP, they fuse into ONE note of tier t+1. Cascades upward.
  - WIN: every wallet empty OR uniform (all notes same tier).

Levels are generated by sampling random low-tier boards and keeping only those
BFS proves solvable AND whose optimal length (par) falls in the difficulty band
for that level slot. Guarantees: solvable, varied, monotonic-ish difficulty.
"""
import json, random, os, sys
from collections import deque

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "levels.json")
SEED = 20260628
TOP = 2          # tiers 0,1,2  -> $1,$5,$20 visible merges (banks at tier 2 or uniform)
MERGE_N = 4      # 4 same-tier fuse into next tier

def cascade(notes):
    ch = True
    while ch:
        ch = False
        if len(notes) >= MERGE_N:
            t = notes[-1]
            if t < TOP:
                run = 0
                for k in range(len(notes) - 1, -1, -1):
                    if notes[k] == t: run += 1
                    else: break
                if run >= MERGE_N:
                    del notes[len(notes) - MERGE_N:]
                    notes.append(t + 1)
                    ch = True
    return notes

def legal(state, cap):
    out = []
    for i, wi in enumerate(state):
        if not wi: continue
        t = wi[-1]
        uni = all(n == wi[0] for n in wi)
        for j, wj in enumerate(state):
            if i == j or len(wj) >= cap: continue
            if not wj:
                if not uni: out.append((i, j))
            elif wj[-1] == t:
                out.append((i, j))
    return out

def apply_mv(state, mv, cap):
    i, j = mv
    s = [list(w) for w in state]
    t = s[i][-1]; run = 0
    for k in range(len(s[i]) - 1, -1, -1):
        if s[i][k] == t: run += 1
        else: break
    k = min(run, cap - len(s[j]))
    for _ in range(k): s[j].append(s[i].pop())
    cascade(s[j])
    return tuple(tuple(w) for w in s)

def win(state):
    return all(len(w) == 0 or all(n == w[0] for n in w) for w in state)

def ser(state):
    return '|'.join(sorted(','.join(map(str, w)) for w in state))

def bfs_par(state, cap, node_cap=160000):
    if win(state): return 0
    seen = {ser(state)}; q = deque([(state, 0)]); nodes = 0
    while q:
        cur, d = q.popleft(); nodes += 1
        if nodes > node_cap: return None
        for mv in legal(cur, cap):
            nx = apply_mv(cur, mv, cap)
            key = ser(nx)
            if key in seen: continue
            if win(nx): return d + 1
            seen.add(key); q.append((nx, d + 1))
    return None

def gen_board(cap, n_tubes, n_filled, fill_per, tier1_p, rng):
    pool = []
    for _ in range(n_filled * fill_per):
        pool.append(1 if rng.random() < tier1_p else 0)
    rng.shuffle(pool)
    tubes = [[] for _ in range(n_tubes)]
    idx = 0
    for ti in range(n_filled):
        for _ in range(fill_per):
            if idx < len(pool):
                tubes[ti].append(pool[idx]); idx += 1
    return tuple(tuple(t) for t in tubes)

def slot_params(idx):
    """Return (cap, n_tubes, n_filled, fill_per, tier1_p, par_min, par_max) for level idx (0..119)."""
    f = idx / 119
    if f < 0.25:        # 1-30 gentle
        cap = 5; tubes = 4 + (idx % 2); filled = 2; fill = 4; t1p = 0.10
        pmin, pmax = 2 + idx // 8, 6 + idx // 6
    elif f < 0.55:      # 31-66 medium
        cap = 6; tubes = 5; filled = 3; fill = 5; t1p = 0.18
        pmin, pmax = 5, 12
    elif f < 0.82:      # 67-98 hard
        cap = 6; tubes = 5 + (idx % 2); filled = 3; fill = 6; t1p = 0.25
        pmin, pmax = 8, 16
    else:               # 99-120 expert
        cap = 6; tubes = 6; filled = 4; fill = 6; t1p = 0.30
        pmin, pmax = 11, 22
    return cap, tubes, filled, fill, t1p, pmin, pmax

def main():
    rng = random.Random(SEED)
    levels = []
    for idx in range(120):
        cap, tubes, filled, fill, t1p, pmin, pmax = slot_params(idx)
        chosen = None; chosen_par = None; relax = 0
        for attempt in range(1200):
            b = gen_board(cap, tubes, filled, fill, t1p, rng)
            if win(b): continue
            p = bfs_par(b, cap)
            if p is None: continue
            lo = max(2, pmin - relax)
            hi = pmax + relax
            if lo <= p <= hi:
                chosen = b; chosen_par = p; break
            # progressively relax the band so we never fail to fill a slot
            if attempt and attempt % 200 == 0:
                relax += 2
        if chosen is None:
            # last resort: any solvable
            for _ in range(400):
                b = gen_board(cap, tubes, filled, fill, t1p, rng)
                if win(b): continue
                p = bfs_par(b, cap)
                if p and p >= 2:
                    chosen = b; chosen_par = p; break
        if chosen is None:
            print(f"FATAL: could not generate level {idx+1}", file=sys.stderr)
            sys.exit(1)
        # pad wallet list so all levels render consistently (trailing empties)
        wl = [list(w) for w in chosen]
        levels.append({
            "level": idx + 1,
            "capacity": cap,
            "tiers": TOP + 1,
            "mergeN": MERGE_N,
            "wallets": wl,
            "par": chosen_par,
        })
    json.dump(levels, open(OUT, "w"))
    pars = [L["par"] for L in levels]
    print(f"wrote {len(levels)} levels -> {os.path.relpath(OUT)}")
    print(f"par range {min(pars)}-{max(pars)}, mean {sum(pars)/len(pars):.1f}")
    # quick monotonic sanity: mean par of first vs last quartile
    q = len(pars)//4
    print(f"par mean Q1={sum(pars[:q])/q:.1f}  Q4={sum(pars[-q:])/q:.1f}")

if __name__ == "__main__":
    main()
